### ISSUE TITLE
Allow non-simulated variables to be a conditional in a simulation capture

### ISSUE THREAD

**Issue by SlimRunner** [jared-hughes/desmodder-gif-creator#9]
**Edit: don't waste time reading this. See the last comment**

My reasoning here is that many of my simulated graphs have a master switch (a non-simulated variable) that kicks off the simulation when set to 1, and I noticed that the conditional for sim-capture is a Desmos "boolean" expression wrapped in a piecewise which is then evaluated in a HelperExpression.

However, when I try to reference my non-simulated variable DesModder prevents me from capturing video. Is the following warning the reason why you disallowed this behavior?

https://github.com/jared-hughes/desmodder-video-creator/blob/536a0c3a6ad60bb50f63dbe84b7da45e89458d6f/Controller.ts#L437-L439

**Comment by SlimRunner** [comment]
I clicked close by mistake thinking it was going to ask me first... sorry

**Comment by SlimRunner** [comment]
So I have some counter arguments for myself here. I just noticed that it is not disallowing me from using non-simulated variables, but it won't let me capture until the condition is true.

It's kind of a separate issue now then. I think my feature request is to allow auto-capturing as soon as the condition becomes true. I'm going to close this issue because it's misleading as is.

**Comment by jared-hughes** [comment]
It may be more clear if #1 is implemented, so it would show a warning "condition not met."
